apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: zep-nlp-hpa
  namespace: zep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zep-nlp
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50